### ISSUE TITLE
ImmersiveTouch broken in 2021.1.2 Build 1088

### ISSUE THREAD

**Issue by qdot** [ImTiara/ImmersiveTouch#1]
As of Client version 2021.1.2 Build 1088 (released 2021-05-03), ImmersiveTouch crashes on startup. NullObjectReferenceException on startup, after the local avatar loads in.

From some quick poking, it looks like might be something wrong with the hook setup for the avatarChangedDelegate, but I couldn't really say what because I'm still not super familiar with MelonLoader and the VRC API, so take that with a grain of salt.

**Comment by ImTiara** [comment]
Hi,
Just tested and ImmersiveTouch still works just fine.
Are you using MelonLoader version 0.3.0?

Did you immediately re-generate the assemblies right after the game update was released?
A possible fix would be to re-install MelonLoader.

**Comment by qdot** [comment]
Yup, using MelonLoader 0.3.0 (Immersive Touch was fine pre-1088). Regenerated assemblies and re-installed MelonLoader on client update, so that was pre-report. I'll give it a shot again tonight and provide some stacks if things are still wonky, or else will just close this if I can't replicate.

**Comment by qdot** [comment]
Ok, rebuilt my setup and now can't repro the issue, so this may have been a symptom of other breakage (MultiplayerDynBones/VibeGoesBrrr were also broken, everything is patched and happy now).

Closing, thanks for the great plugin!
